name: Google Sheets Duty Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "59 22 * * *"

permissions:
  contents: read

jobs:
  run-bot:
    name: Run duty checker bot
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      SHEET_NAME: ${{ secrets.SHEET_NAME }}
      USER_NAME: ${{ secrets.USER_NAME }}
      API_URL: ${{ secrets.API_URL }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      APP_ENV: prod
      LOG_LEVEL: info

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: go.sum

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Write credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/credentials.json

      - name: Build
        run: |
          go build -trimpath -ldflags="-s -w -X main.Version=${GITHUB_SHA::7}" -o bot ./cmd/bot

      - name: Run bot
        run: ./bot